### ISSUE TITLE
Click Export to Readwise then nothing

### ISSUE THREAD

**Issue by MrMarc** [micahlt/scribd-readwise-integration#1]
As the title says.

Click the extension button, the notes and bookmarks appear. 
Click the extension again ... Export to Readwise appears and click that
It then says "Exporting" but then nothing downloads and nothing appears in readwise

**Comment by micahlt** [comment]
Hi Marc - thanks for trying out the extension!  I'm going to put out a video demo very soon explaining how to use the extension.  In order for it to work correctly, you must be logged into Readwise and Scribd.  You then open a book in  Scribd, use the extension, and then Readwise should open with the imported content.

**Comment by MrMarc** [comment]
Thanks for responding!

I had them both open in Chrome right next to each other. I can create a quick screen grab video if you want.

**Comment by micahlt** [comment]
Just took a look and it appears that Readwise changed something about how their access token is stored.  I've submitted an update to the extension that should fix the issue.  Until it's published, try editing some detail about a book which should add the access token to your browser cookies.  Feel free to upload a screengrab if it's still not working after you do that!

Here's the a summary video that might help as well: https://youtu.be/M3VYlBtt9aE

**Comment by micahlt** [comment]
@MrMarc the extension update has been published - everything should be working correctly now!
