### ISSUE TITLE
scribd now everand

### ISSUE THREAD

**Issue by kjguenther** [micahlt/scribd-readwise-integration#2]
I just tried the extension in Everand (the new name for Scribd), and it does not work there. Can the extension be updated to include Everand?

**Comment by micahlt** [comment]
I was not aware that Scribd has been renamed!  I'll work on this ASAP!

**Comment by micahlt** [comment]
@kjguenther I've just published an update on the Chrome Store that should remedy your issue!

**Comment by kjguenther** [comment]
Thank you, Micah. It works!
